export const tools = [
  { id: 'qr', name: '二维码', icon: '📱', desc: '生成二维码' },
  { id: 'unit', name: '单位换算', icon: '📐', desc: '长度、重量、温度等单位转换' },
  { id: 'base', name: '进制转换', icon: '🔢', desc: '二进制、八进制、十进制、十六进制' },
  { id: 'color', name: '颜色工具', icon: '🎨', desc: 'HEX / RGB / HSL 互转' },
  { id: 'text', name: '文字统计', icon: '📝', desc: '字数、词数、行数统计' },
  { id: 'encrypt', name: '加密解密', icon: '🔐', desc: 'AES / DES / Base64 加解密' },
  { id: 'img-compress', name: '图片压缩', icon: '🖼️', desc: '在线压缩图片大小' },
  { id: 'random', name: '随机数', icon: '🎲', desc: '生成指定范围随机数' },
  { id: 'password', name: '密码生成', icon: '🔑', desc: '生成安全随机密码' },
  { id: 'countdown', name: '倒计时', icon: '⏳', desc: '设置倒计时提醒' },
  { id: 'calc', name: '计算器', icon: '🧮', desc: '科学计算器' },
  { id: 'clock', name: '世界时钟', icon: '🌍', desc: '查看各地当前时间' },
  { id: 'bmi', name: 'BMI 计算', icon: '⚖️', desc: '身体质量指数计算' },
  { id: 'ip', name: 'IP 查询', icon: '🌐', desc: '查询本机 IP 信息' },
  { id: 'json', name: 'JSON 格式化', icon: '{ }', desc: '格式化和压缩 JSON' },
  { id: 'base64', name: 'Base64', icon: '📋', desc: 'Base64 编码解码' },
  { id: 'urlcode', name: 'URL 编解码', icon: '🔗', desc: 'URL 编码和解码' },
  { id: 'hash', name: '哈希生成', icon: '#️⃣', desc: 'MD5 / SHA1 / SHA256' },
  { id: 'lorem', name: 'Lorem Ipsum', icon: '📄', desc: '生成占位文本' },
  { id: 'regex', name: '正则测试', icon: '🔍', desc: '正则表达式在线测试' },
  { id: 'timestamp', name: '时间戳', icon: '⏰', desc: '时间戳与日期互转' },
  { id: 'morse', name: '摩尔斯电码', icon: '📡', desc: '摩尔斯电码编解码' },
  { id: 'img-base64', name: '图片转Base64', icon: '📸', desc: '图片与Base64互转' },
  { id: 'diff', name: '文本对比', icon: '🔀', desc: '对比两段文本差异' },
  { id: 'pinyin', name: '汉字转拼音', icon: '🀄', desc: '中文转拼音标注' },
  { id: 'pdf-word', name: 'PDF 转 Word', icon: '📄', desc: 'PDF 转换为可编辑 Word' },
  { id: 'merge-pdf', name: '合并 PDF', icon: '📑', desc: '多个 PDF 合并为一个' },
  { id: 'split-pdf', name: '拆分 PDF', icon: '✂️', desc: '按页拆分 PDF 文件' },
  { id: 'compress-pdf', name: '压缩 PDF', icon: '🗜️', desc: '减小 PDF 文件大小' },
  { id: 'pdf-jpg', name: 'PDF 转 JPG', icon: '🖼️', desc: 'PDF 每页转为图片' },
  { id: 'jpg-pdf', name: 'JPG 转 PDF', icon: '📸', desc: '图片合并为 PDF' },
  { id: 'protect-pdf', name: '加密 PDF', icon: '🔒', desc: '为 PDF 设置密码' },
  { id: 'unlock-pdf', name: '解锁 PDF', icon: '🔓', desc: '移除 PDF 密码保护' },
]
